version: '3.7'

services:
  go-simple-rest:
    build: .
    command: ./bin/rest-service
    depends_on:
      - go-simple-mysql
    ports:
      - 9200:8080
    environment:
      DB_MAX_IDLE_CONN: 10
      DB_MAX_OPEN_CONN: 100
      DB_NAME_MYSQL: simpledb
      DB_USER_MYSQL: VywiNaohioeuTWLp
      DB_PASSWORD_MYSQL: uxjgLBfObrPbTqcVNUqgAZWytJRLamfI
      DB_HOST_MYSQL: kumparan-mysql
      DB_PORT_MYSQL: 3306

  go-simple-mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: simpledb
      MYSQL_USER: VywiNaohioeuTWLp
      MYSQL_PASSWORD: uxjgLBfObrPbTqcVNUqgAZWytJRLamfI
      MYSQL_ROOT_PASSWORD: VywiNaohioeuTWLp
      MYSQL_ALLOW_EMPTY_PASSWORD: VywiNaohioeuTWLp
      MYSQL_RANDOM_ROOT_PASSWORD: VywiNaohioeuTWLp
    volumes:
      - ./data/mysql:/var/lib/mysql


  # volumes:
  #   mysql-db:
