definitions:
  model.Response:
    properties:
      data:
        type: object
      error:
        type: object
      log_id:
        type: string
      message:
        type: object
      status:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/article/create:
    post:
      consumes:
      - '*/*'
      description: create article
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: Create Article
      tags:
      - Article Management
  /api/v1/article/list:
    get:
      consumes:
      - '*/*'
      description: get all list article
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: interface
      summary: Get Article List
      tags:
      - Article Management
swagger: "2.0"
